### ISSUE TITLE
[Errno 98] Address already in use

### ISSUE THREAD

**Issue by bohlender** [LukasBoersma/Hexxagon#2]
After executing `run_tests.py`, running it again within 60s will throw `OSError: [Errno 98] Address already in use`.

This behaviour of the socket is by design [[1](https://stackoverflow.com/questions/337115/setting-time-wait-tcp),[2](http://www.serverframework.com/asynchronousevents/2011/01/time-wait-and-its-design-implications-for-protocols-and-scalable-servers.html)]. After session shutdown the socket stays in a waiting state for `TIME_WAIT` seconds (defaults to 60s), waiting for potentially delayed packets to arrive, before actually freeing the address & port.

While closing the shell that executes `run_tests.py` is a workaround -- enforcing termination without waiting -- this should not be necessary.

For example, we could allow reuse of the address via
```python
def __init__(self, player_count, timeout):
    self.listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    self.listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1) # Enable reuse
    ...
```
or use the next free port.

**Comment by LukasBoersma** [comment]
Fixed in 6dafc402c1d4a7e5b107055a30cc07d4df105cf2 :)
